apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    label:
        labelA: A
type: Opaque
data:
    username: ENC[AES256_GCM,data:xgL9l2DAYMo=,iv:Vv25BWkRCl26kI1ZejV9JTAWal4VG4CBoaucXiUtLYk=,tag:pC6BWj1pqI/ImGpHiDA1Vw==,type:str]
    password: ENC[AES256_GCM,data:As4SUwHu08guWO/eChGpWw==,iv:746UsMnDFqJV8FcK4BJGz0oMmV72p3W49Rjqkr6sCyg=,tag:pENwhM2FnsQwPlp93p1wdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17tjuqm5efucf9u6ev47hmwfpzfsvlw0vhvjdvp868a940f23rf4q5cxaxg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWlY2YXoyZVZVMUVpVzhS
            R3JOdzRuWU0vb1cyeElQemhvb0Nwd2dlS1dvCjRxVXd2WEJqQldZZGlndXdRMFpj
            MWZZSVJOdWlWNGI3YThPZVhBdTdXQ1kKLS0tIDJ3M1hCeTI5OS9xVHNYcnh6Tm1J
            NGc3UjlBZ3VMQlZXUnFNOWlGY2l6QjQK7xCw/IP3Hby7c9AuZHmuWwA/uoDk5sUw
            CsAm2zaz5W69I0nlG8wNn63C/S/S3AI5tsEYzSPDTXeMZrbYm8PhUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T11:59:37Z"
    mac: ENC[AES256_GCM,data:UChRT3nq7lcmJwDDT2LgGU18mj8wpUDbF7B/e3FCMuPQQ3dnlsLSJXOHndDDfBizz2FySFhDs8SikdTRf8xRnxK3dQFiq/ktGBGbT0I3R5ZMB6lXlbEjUQaTP/IbmwWs3mNaJ1p+iLTFCYgM4nywMLEld8etKWsLIIpQU2+guBQ=,iv:LzpMRw5t1VD1RWWQyyEUqGoC1l7zyXhZAgyAM72WGMM=,tag:77EMftZLbOsxJWMNSclHuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
